### ISSUE TITLE
Where is the user data folder on Android?

### ISSUE THREAD

**Issue by thomaspdt** [johannesjo/super-productivity-android#12]
I would like to sync the user data folders with Syncthing. For that, I need to know where the user data folder is in Android.

I checked under Android/data/, looking for something like a com.superproductivity folder, but couldn't find anything.

Also, there is not option for automatic backup in the Android app, so I wasn't able to find the path like I did on Linux.

Could you tell me where the user data folder is?

Thanks

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. 

I am not sure myself to be honest. Maybe this helps:
https://android.stackexchange.com/questions/47924/where-android-apps-store-data#:~:text=All%20apps%20(root%20or%20not,all%20other%20data%20go%20here.
?

I doubt that syncing like this would work very well, at least not if the app is running during the sync. There are likely to be problems if that happens.

There are currently no automated backups for the android version.

**Comment by tzawlxih** [comment]
Probably he is in need for LocalFile sync as is present in PC version.

**Comment by johannesjo** [comment]
Btw. this is an issue. For questions please use the discussions page:
https://github.com/johannesjo/super-productivity/discussions

**Comment by mortbauer** [comment]
Hello @johannesjo, I think this is still open right? and the discussions link from above seems not to work.

It is really a great app, hope I manage to make it work to sync.

**Comment by johannesjo** [comment]
Hey @mortbauer ! What do you want to achieve? Here is the link:
https://github.com/johannesjo/super-productivity/discussions
