### ISSUE TITLE
App fix and overhaul

### ISSUE THREAD

**Issue by berhram** [johannesjo/super-productivity-android#28]
Hello.
Great app (web), can't use the Android version because of broken. Many deprecated APIs are used (which means that the app will not work in the latest androids versions). Also, there are dangerously debugging that need to be deleted (e.g. with proguard rules).
I'm an Android developer and will be happy to help. Rewrite to Kotlin or fix the existing codebase, it doesn't matter.

**Comment by johannesjo** [comment]
Hey @berhram ! That's great news! Help would be very welcome indeed! Where would you like to start? How can I help?

**Comment by berhram** [comment]
> Hey @berhram ! That's great news! Help would be very welcome indeed! Where would you like to start? How can I help?

I'll start to work on this ASAP and if necessary, I will ask for clarification in this issue
