### ISSUE TITLE
Keep "Finish day" as an option before closing the app

### ISSUE THREAD

**Issue by detectivepikachu** [johannesjo/super-productivity-android#30]
## :person_frowning: Problem Statement
Once opened, whenever I have to close the app it compulsorily asks me to finish the day and move the done tasks to archive or just stay.

## :grey_question: Possible Solution
It would be great to have a check box kind of a thing in the settings where one could opt for closing the app to "finish day" or just keep everything as it is until returned to by opening the app.

## :arrow_heading_up: Describe alternatives you've considered

Something like:

- [ ]  **Finish day** when closing the app
     *If left unchecked you won't be asked to finish the day and put the completed tasks in archive when closing the app and will return to the same workflow when reopened*

**Comment by johannesjo** [comment]
You should be able to do this with the "Confirm before exiting the app without finishing day first" setting.

**Comment by detectivepikachu** [comment]
OH YES! couldn't get the wording before. Thank you so much and sorry!
