### ISSUE TITLE
impossible to complete a task in Android version 7.16.

### ISSUE THREAD

**Issue by eeroolli** [johannesjo/super-productivity-android#46]
## :ghost: Brief Description

I use the windows version all the time. When a task is running next to the title are three icons: Remove from my day, Completed, Show additional info.  In Android version haven't found a way to complete a task as there are no such icons visible.

## :pancakes: Action version

Version of the Action where you are encountering the issue.

## :tophat: workflow configuration

I am running Super Productivity 7.16 for Android on Redmi Note 10 pro , which runs Android 12 SKQ1.210908 and MIUI Global version 13.0.16.

## Steps To Reproduce

1. Go to Today. Now  you see all task scheduled for today.
2. Select any of the tasks 
3. Click on 'Run/play'
4. Try to mark the task as completed.  

## :police_car: Expected behavior

There should be a  :heavy_check_mark: icon so that the task or subtask can be completed.

## :heavy_plus_sign: Additional context

It is a great program.  Thank you all!

**Comment by johannesjo** [comment]
Swiping the task to the right will do the trick!
