### ISSUE TITLE
Download .apk from github directly with Obtainium

### ISSUE THREAD

**Issue by HomemadeAdvanced** [johannesjo/super-productivity-android#47]
I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly from github?

**Comment by johannesjo** [comment]
This is more of a [discussion](https://github.com/johannesjo/super-productivity-android/discussions) than an issue. Can you restate your question there?

I also think there should be some info somewhere  already, as I remember talking about this before.

**Comment by HomemadeAdvanced** [comment]
Allright, there is no problem to open a discussion for that, but your link is dead and I cannot find a discussions tab.

**Comment by johannesjo** [comment]
Ah sorry. Wrong repository :)
https://github.com/johannesjo/super-productivity/discussions

**Comment by HomemadeAdvanced** [comment]
Allright I found the discussion. Thanks. https://github.com/johannesjo/super-productivity/discussions/2974
