### ISSUE TITLE
Notifications appear blank or incomplete on Xiaomi devices, but display correctly on other devices like Huawei

### ISSUE THREAD

**Issue by jiongxuan** [johannesjo/super-productivity-android#49]
## :ghost: Brief Description

On Xiaomi devices, notifications occasionally appear blank or incomplete. This issue does not occur on other devices like Huawei, where notifications display correctly.

## :pancakes: Action version

App Version: V23.0.0 (Google Play)  
Server Version: Not specific (tested on 9.0.7)

## :tophat: Workflow Configuration

Your workflow configuration may vary, but this issue can be reproduced with any method that triggers a notification. In my case, I used Scheduled At to trigger the notification at a specific time, but other triggers will also reproduce the issue.

## Steps To Reproduce

1. Schedule or trigger a notification using any method (e.g., Scheduled At).
2. Wait for the notification to be displayed.
3. On a Xiaomi device, observe the notification. The notification may appear blank or only partially complete (see attached screenshot).
4. Compare with the same notification on a different device like Huawei, where the notification displays as expected.

## :police_car: Expected behavior

The notification should be displayed correctly on all Android devices, showing both the title and body text in both collapsed and expanded views.

## :heavy_plus_sign: Additional context

I have identified the problem in the code and will fix this issue within the next few days. After self-testing, I will submit a PR to address this.

**Screenshots:**  
![IMG_0120](https://github.com/user-attachments/assets/da710061-aac2-4035-a349-d826ecdcd901)

**Comment by jiongxuan** [comment]
I see the PR has been accepted, thank you! 

Do you think we should wait until the next version to close the issue, or close it now?

**Comment by johannesjo** [comment]
We should close it now! :) Thanks for the reminder!

This is really helpful to me, since I am not very experienced with android development. Thank you very much for your work!

**Comment by jiongxuan** [comment]
Thank you for your kind words! I’m glad I could help.

With over 15 years of mobile development experience, I’m always happy to contribute in any way I can. I believe that by working together, we can make this project even better. 

If you need any further assistance with Android/iOS development or anything else, feel free to reach out. Looking forward to seeing the continued success of this project!

**Comment by johannesjo** [comment]
Thank you! That's great to hear! The android app can definitely use some work, although it is getting better little by little :)
