### ISSUE TITLE
Fail to sync with Google Drive

### ISSUE THREAD

**Issue by guludo** [johannesjo/super-productivity-android#5]
### :speaking_head: Foreword

> Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

And thank you for writing the Super Productivity app :slightly_smiling_face: 

## :ghost: Brief Description

I already am using Super Productivity on my laptop and wanted to use it on my Android as well. I receive an error when trying to configure synchronization via Google Drive.

## Steps To Reproduce

1. Start the app;
2. Go to 'Settings';
3. Scroll down to 'Sync & Export' session;
4. Expand the 'Sync' panel;
5. Select GoogleDrive as the Sync Provider;
6. Tap 'Save';
7. A dialog should appear to select the Google account. Select the desired Google account to use;
8. See the error `Google Drive: Error while creating sync file. [object Object]`.

## :police_car: Expected behavior

The synchronization configuration working.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting this! I am a bit stuck with this. Currently, progress is tracked here (though this repo might be the actual right place for it...):
https://github.com/johannesjo/super-productivity/issues/434

**Comment by johannesjo** [comment]
This should work now with the latest release.
