### ISSUE TITLE
Back button behaviour inconsistent with Android UX

### ISSUE THREAD

**Issue by lukeduncan-scot** [johannesjo/super-productivity-android#6]
## :ghost: Brief Description

When navigating through the app, especially between top-level navigation points such as those found under the hamburger menu (Today, Scheduled, Project Foo etc...), I would expect interaction with the back button to navigate to the previous screen.

## Steps To Reproduce

1. Open App
1. See **Today** screen
1. Tap icon for navigation menu
1. Navigate to another screen, **Scheduled** for example
1. Tap device's back button
1. App closes

## :police_car: Expected behavior

1. Open App
1. See **Today** screen
1. Tap icon for navigation menu
1. Navigate to another screen, **Scheduled** for example
1. Tap device's back button
1. Navigate back to **Today** screen

## Suggestions

You can capture the back button event before it is delegated to the system by overriding `onBackPressed()` in an `Activity`.
In the case of this app, I think you could override in `FullscreenActivity` following the tips here: https://developer.android.com/guide/navigation/navigation-custom-back#implement_custom_back_navigation

## :heavy_plus_sign: Additional context

Some context around the back behaviour: https://developer.android.com/guide/components/activities/tasks-and-back-stack

**Comment by Rodeo-McCabe** [comment]
I've also experienced this. I find it particularly frustrating since the app takes about a minute to load, so accidentally hitting the back button by force of habit causes quite an interruption.

**Comment by zoli** [comment]
I would like to take on this.

**Comment by johannesjo** [comment]
@zoli there is an open but abandoned PR for this:
https://github.com/johannesjo/super-productivity-android/pull/7
